---
- name: Install haproxy and openssl
  apt:
    name:
      - haproxy
      - openssl
    state: present
    update_cache: yes

- name: Create HAProxy certs directory
  file:
    path: /etc/haproxy/certs
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create HAProxy cert directory
  file:
    path: /etc/haproxy/certs
    state: directory
    mode: '0755'

- name: Create HAProxy PEM from Let's Encrypt certificate
  shell: |
    cat \
    /etc/letsencrypt/live/ansible.ehjoz.app/fullchain.pem \
    /etc/letsencrypt/live/ansible.ehjoz.app/privkey.pem \
    > /etc/haproxy/certs/ansible.ehjoz.app.pem
  args:
    executable: /bin/bash

- name: Combine GREEN SSL certificate and key for HAProxy
  shell: |
    cat /etc/letsencrypt/live/green.ansible.ehjoz.app/fullchain.pem \
        /etc/letsencrypt/live/green.ansible.ehjoz.app/privkey.pem \
        > /etc/haproxy/certs/green.ansible.ehjoz.app.pem
  args:
    creates: /etc/haproxy/certs/green.ansible.ehjoz.app.pem

- name: Set PEM permissions
  file:
    path: /etc/haproxy/certs/ansible.ehjoz.app.pem
    mode: '0600'


- name: Copy HAProxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: Check HAProxy config
  command: haproxy -c -f /etc/haproxy/haproxy.cfg
  changed_when: false

- name: Restart HAProxy
  systemd:
    name: haproxy
    state: restarted
    enabled: yes
