---
- name: Install bind9 packages
  apt:
    name:
      - bind9
      - bind9-utils
      - bind9-doc
    state: present
    update_cache: yes

- name: Copy BIND local config
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: '0644'

- name: Copy first-test.de zone file
  template:
    src: db.first-test.de.j2
    dest: /etc/bind/db.first-test.de
    owner: root
    group: bind
    mode: '0644'

- name: Check BIND config syntax
  command: named-checkconf
  changed_when: false

- name: Check first-test.de zone
  command: named-checkzone first-test.de /etc/bind/db.first-test.de
  changed_when: false

- name: Restart bind9
  systemd:
    name: bind9
    state: restarted
    enabled: yes
