name: Ansible CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  ci:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Ansible
        run: |
          ansible --version

      - name: Check Ansible syntax
        run: |
          ansible-playbook -i inventory.ini site.yml --syntax-check

      - name: Check project structure
        run: |
          test -f site.yml
          test -f inventory.ini
          test -d roles/node_apps
          test -d roles/nginx
          test -d roles/bind
          test -d roles/haproxy

  deploy:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create local Ansible inventory
        run: |
          cat > local_inventory.ini <<EOF
          [vps]
          localhost ansible_connection=local
          EOF

      - name: Deploy locally with Ansible
        env:
          BECOME_PASSWORD: ${{ secrets.VPS_ANSIBLE_BECOME_PASSWORD }}
        run: |
          ansible-playbook \
            -i local_inventory.ini \
            site.yml \
            -e ansible_become_password="$BECOME_PASSWORD"

      - name: Test deployed apps
        run: |
          curl -fsS https://ansible.ehjoz.app/app1
          echo
          curl -fsS https://ansible.ehjoz.app/app2
          echo